---
- name: Kubernetes + DevOps Toolchain Setup
  hosts: all
  become: true
  vars:
    kubectl_version: "v1.29.0"
    helm_version: "v3.14.0"
    kind_version: "v0.22.0"
    argocd_namespace: argocd
    user_name: "{{ ansible_user }}"

  tasks:

  - name: Update apt cache and upgrade system
    apt:
      update_cache: yes
      upgrade: dist

  # ---------------- Docker ----------------
  - name: Install Docker dependencies
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present

  - name: Add Docker GPG key
    shell: |
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    args:
      creates: /usr/share/keyrings/docker-archive-keyring.gpg

  - name: Add Docker repository
    apt_repository:
      repo: >
        deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
        https://download.docker.com/linux/ubuntu
        {{ ansible_lsb.codename }} stable
      state: present

  - name: Install Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: Enable and start Docker
    service:
      name: docker
      state: started
      enabled: true

  - name: Add user to docker group
    user:
      name: "{{ user_name }}"
      groups: docker
      append: yes

  # ---------------- kubectl ----------------
  - name: Install kubectl
    get_url:
      url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
      dest: /usr/local/bin/kubectl
      mode: '0755'

  # ---------------- kind ----------------
  - name: Install kind
    get_url:
      url: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"
      dest: /usr/local/bin/kind
      mode: '0755'

  # ---------------- helm ----------------
  - name: Install Helm
    unarchive:
      src: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
      dest: /tmp
      remote_src: yes

  - name: Move helm binary
    copy:
      src: /tmp/linux-amd64/helm
      dest: /usr/local/bin/helm
      mode: '0755'
      remote_src: yes

  # ---------------- k3s ----------------
  - name: Install k3s
    shell: |
      curl -sfL https://get.k3s.io | sh -
    args:
      creates: /usr/local/bin/k3s

  # ---------------- kind cluster ----------------
  - name: Create kind cluster
    become: false
    shell: |
      kind create cluster --name dev-cluster
    args:
      creates: "{{ ansible_env.HOME }}/.kube/config"

  # ---------------- Argo CD ----------------
  - name: Create argocd namespace
    become: false
    shell: |
      kubectl create namespace {{ argocd_namespace }} || true

  - name: Install Argo CD
    become: false
    shell: |
      kubectl apply -n {{ argocd_namespace }} \
      -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

  - name: Wait for Argo CD server to be ready
    become: false
    shell: |
      kubectl rollout status deployment/argocd-server -n {{ argocd_namespace }}
    retries: 10
    delay: 30
    register: rollout_result
    until: rollout_result.rc == 0

  # ---------------- Port Forward ----------------
  - name: Port forward Argo CD server
    become: false
    shell: |
      kubectl port-forward svc/argocd-server -n {{ argocd_namespace }} 8080:443
    async: 3600
    poll: 0
