apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tickets-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/beltawn3507/ticket_app_cd.git
    targetRevision: main
    path: tickets   # <-- directory containing deployment.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
