apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tickets-depl.yaml
  - tickets-mongo-depl.yaml

images:
  - name: ghcr.io/beltawn3507/tickets
    newTag: 52a9959a732f0c9e0cef6b63ded2545764de04c7

